
export const LOAD_TODOS = "LOAD_TODOS_ACTION";
export const ADD_TODO = "ADD_TODO_ACTION";
export const TOGGLE_ALL = "TOGGLE_ALL_ACTION";
export const TOGGLE_TODO = "TOGGLE_TODO_ACTION";
export const DELETE_TODO = "DELETE_TODO_ACTION";
export const CLEAR_ALL = "CLEAR_ALL_ACTION";
